# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc2e88e8c114901a540d6718dda6bc33f00f2f7c7e26aeed5fa7cf847c6541b1051d11dbc2ae976c6488c9ccd3d38bc4ccf143c1d21937257535945f1430c76

test:
  secret_key_base: e08f29153df1f468013b81fd7abb49441e5ec5545a762b05e1e200fa74b45bce3938431beb9ba3f03dcb0897c24493d099585d3a909acb5f894d659e55f46ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
